server:
  port: ${SERVER_PORT:8081}

app:
  cors:
    origins: ${CORS_ORIGINS:http://localhost:3000}
  keycloak:
    admin:
      server-url: ${KEYCLOAK_ADMIN_SERVER_URL:http://keycloak:8080}
      realm: ${KEYCLOAK_REALM:demo}
      admin-realm: master
      client-id: admin-cli
      username: ${KEYCLOAK_ADMIN_USERNAME:admin}
      password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

spring:
  datasource:
    url: ${APP_DB_URL:jdbc:postgresql://postgres:5432/demo_app}
    username: ${APP_DB_USER:keycloak}
    password: ${APP_DB_PASSWORD:keycloak}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8080/realms/demo}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8080/realms/demo/protocol/openid-connect/certs}
